### ISSUE TITLE
Error of a missing lib (help)

### ISSUE THREAD

**Issue by TanZng** [wsdfhjxc/xfce-patches#5]
After running `./autogen.sh --prefix=/usr --libdir=$LIBDIRPATH --libexecdir=$LIBDIRPATH && make`
I got the next "error":
``` bash
checking for libwnck-3.0 >= 3.14... not found
*** The required package libwnck-3.0 was not found on your system.
*** Please install libwnck-3.0 (atleast version 3.14)
```
But actually I have libwnck-3.0

After run `sudo apt-get install libwnck-3.0` i got
``` bash
Note, selecting "libwnck-3-0" for the regular expression "libwnck-3.0"
libwnck-3-0 is already in its latest version (3.36.0-1).
 ```

I'm using Xubuntu => OS: Ubuntu 20.04 LTS x86_64

**Comment by wsdfhjxc** [comment]
You need development packages, which means that, instead of `libwnck-3-0`, you need to get `libwnck-3-dev`.

Actually, most packages in Ubuntu's repositories have their development version marked by a `-dev` suffix, so it's not that hard to discover them, but I have to admit that I could have listed them all properly within the building instructions.

If I get back into Xfce ricing, maybe more updates to this repository will come.

**Comment by wsdfhjxc** [comment]
I'm closing this, but if you have more questions, feel free to ask.
