### ISSUE TITLE
xfwm4 rounded-corners patch: error running git apply

### ISSUE THREAD

**Issue by Vishvamitra** [wsdfhjxc/xfce-patches#7]
Hello! As a premise, this is the first time I've compiled software, so chances are that I missed some basic passages. I'm running Xubuntu 20.04.
So I followed the instructions to build the XFCE 4.14 version and the process went smoothly. Then I navigated to the /home/xfwm4 folder, which is the source folder, I dropped the rounded-corners patch file by clicking "Save link as..." from Chromium (is this the right procedure?) then I typed `git apply xfwm4-4.14.0-rounded-corners.patch && make` but the apply failed and I got this error: `error: unrecognized input`. Then I looked for some solution on the net and I converted the file to UTF-8: no result! I still got the same error.
I tried a second attempt: I removed the patch file and I copy-pasted the code from the patch page into a new vim file called in the exact way as the patch: Now, when I ran git apply on this second attempt I got a different error: `corrupt patch file at line 289`.
What am I doing wrong?

UPDATE:
I was able to make the `git apply` command work by downloading the raw patch file through the `curl -O` command. I placed the patch into the xfwm4/src directory, but when I ran `git apply` for the second time I got this new error:
`error: patch failed: src/frame.c:62
error: src/frame.c: patch does not apply
error: patch failed: src/settings.c:746
error: src/settings.c: patch does not apply
error: patch failed: src/settings.h:245
error: src/settings.h: patch does not apply`
What's happening?

**Comment by wsdfhjxc** [comment]
You need to take the patch file straight from the downloaded repository, either `git clone https://github.com/wsdfhjxc/xfce-patches`, or from the zipped archive downloaded from GitHub. You can also download just the patch file, but you must click the "Raw" button to get the [patch's content](https://raw.githubusercontent.com/wsdfhjxc/xfce-patches/master/xfwm4/xfwm4-4.14.0-rounded-corners.patch) – only then you can click "Save Page As..." or Ctrl+S to save the actual patch file.

But you figured it out with the use of `curl` eventually, so that's great. The patch file should be the correct one.

As for the errors, it seems that you've placed the patch file in the `src` subdirectory, within the `xfwm4` directory. The patch must be placed in the upper `xfwm4` directory, not the `src` subdirectory. It's my bad – unclear instructions, I'll revisit them some day.

**Comment by Vishvamitra** [comment]
First of all, thank you very much for replying to my thread!
Secondly, happy new year :smile: 
Lastly, this morning something very strange happened. I ran xfwm4 --replace to fix my xfwm4 (which stopped working yesterday). Then I moved the patch file into the xfwm4 directory but it didn't work again. The strangest thing, though, is that when I tried to run the `xfconf-query` command to apply rounded corners and to remove window decorations, and they worked splendidly! I'm attaching a screenshot so you can see.

![Screenshot_2021-01-01_12-47-34](https://user-images.githubusercontent.com/40338178/103438150-26524880-4c30-11eb-80a4-9c5c85f6b898.png)

Is this magic :laughing: ? I didn't have to run the patch.

**Comment by wsdfhjxc** [comment]
In all the fuss, you must have applied the patch... somehow. Anyway, I'm glad it does work now :+1: .

**Comment by Vishvamitra** [comment]
Now that I recall, I must have piped the `git apply` command to the `curl` command during one of the first attempts and I can remember that I didn't get any errors back then. The patch must have been applied in that occasion. It's strange that applying the patch doesn't work through the standard command though....Anyways, thank you very much for your support! I'm going to close the thread now.
